### ISSUE TITLE
Hi! Did your NesSharp supports sounds/audiooutput? 

### ISSUE THREAD

**Issue by mediaexplorer74** [stickyPiston/nessharp#1]
Hi! Did your NesSharp supports sounds/audiooutput? Oh, I see that NesSharp is multi-platform. Great wokt/job ! :)
But no UWP support?

**Comment by stickyPiston** [comment]
Hi,

Thanks for showing interest in our project! Quite frankly, I hadn't expected any people popping by, so this is good surprise.

Concerning your question, Nessharp does support audio output, however it might be quite buggy. That is, we implemented the noise, pulse and triangle channels, which cover almost all of the sounds in the major games.
As for the UWP support, we used the Eto (https://github.com/picoe/Eto) GUI framework to encapsulate the SFML window in. Eto doesn't seem to support UWP, as far as I can tell. Therefore, we don't support UWP too.

Cheers
